language: node_js
node_js:
  - "14"
  - "12"
  - "10"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ -n "${PACKAGE-}" ]; then cd "packages/${PACKAGE}"; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
  - 'if [ -n "${ESLINT}" ]; then npm install --no-save "eslint@${ESLINT}"; fi'
  - 'if [ -n "${REACT_HOOKS}" ]; then npm install --no-save "eslint-plugin-react-hooks@${REACT_HOOKS}"; fi'
script:
  - 'if [ -n "${PREPUBLISH-}" ]; then npm run pretravis && npm run prepublish && npm run posttravis; elif [ -n "${LINT-}" ]; then npm run lint; else npm run travis; fi'
sudo: false
env:
  matrix:
    - 'TEST=true ESLINT=7 PACKAGE=eslint-config-airbnb-base'
    - 'TEST=true ESLINT=7 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=7 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=7 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=7 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=6 PACKAGE=eslint-config-airbnb-base'
    - 'TEST=true ESLINT=6 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=6 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=6 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=6 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb-base'
    - 'TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=5 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=5 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=5 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb'
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=7 PACKAGE=eslint-config-airbnb-base
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=7 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=7 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=7 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=7 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=6 PACKAGE=eslint-config-airbnb-base
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=6 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=6 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=6 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=6 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=5 PACKAGE=eslint-config-airbnb-base
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=5 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=5 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=5 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=5 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: LINT=true
    - node_js: "lts/*"
      env: LINT=true PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: LINT=true PACKAGE=eslint-config-airbnb-base
    - node_js: "8"
      env: TEST=true ESLINT=6 PACKAGE=eslint-config-airbnb-base
    - node_js: "8"
      env: TEST=true ESLINT=6 PACKAGE=eslint-config-airbnb
    - node_js: "8"
      env: TEST=true ESLINT=6 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb
    - node_js: "8"
      env: TEST=true ESLINT=6 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb
    - node_js: "8"
      env: TEST=true ESLINT=6 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb
    - node_js: "8"
      env: TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb-base
    - node_js: "8"
      env: TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb
    - node_js: "8"
      env: TEST=true ESLINT=5 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb
    - node_js: "8"
      env: TEST=true ESLINT=5 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb
    - node_js: "8"
      env: TEST=true ESLINT=5 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb
    - node_js: "6"
      env: TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb-base
    - node_js: "6"
      env: TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb
    - node_js: "6"
      env: TEST=true ESLINT=5 REACT_HOOKS=3 PACKAGE=eslint-config-airbnb
    - node_js: "6"
      env: TEST=true ESLINT=5 REACT_HOOKS=2.3 PACKAGE=eslint-config-airbnb
    - node_js: "6"
      env: TEST=true ESLINT=5 REACT_HOOKS=1.7 PACKAGE=eslint-config-airbnb
  exclude:
  allow_failures:
    - env: PREPUBLISH=true ESLINT=6 PACKAGE=eslint-config-airbnb-base
    - env: PREPUBLISH=true ESLINT=6 PACKAGE=eslint-config-airbnb
    - env: PREPUBLISH=true ESLINT=5 PACKAGE=eslint-config-airbnb-base
    - env: PREPUBLISH=true ESLINT=5 PACKAGE=eslint-config-airbnb
